# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 07:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': '\u76f8\u540c\u767b\u5f55\u540d\u7684\u7528\u6237\u5df2\u7ecf\u5b58\u5728'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='\u7528\u6237\u540d')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u542f\u7528')),
                ('is_staff', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u4ee5\u767b\u5f55\u540e\u53f0')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('type', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7c7b\u522b')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='\u89d2\u8272')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
            ],
            options={
                'verbose_name': '\u533a\u53bf',
                'verbose_name_plural': '\u533a\u53bf',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8eab\u4efd')),
            ],
            options={
                'verbose_name': '\u8eab\u4efd',
                'verbose_name_plural': '\u8eab\u4efd',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
                ('price', models.IntegerField(verbose_name='\u4ef7\u683c')),
                ('type', models.SmallIntegerField(choices=[(1, '\u5c0f\u65f6'), (2, '\u5929')], default=1, verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u79d1\u76ee',
                'verbose_name_plural': '\u6388\u8bfe\u79d1\u76ee',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(1, '\u7537'), (2, '\u5973')], verbose_name='\u6027\u522b')),
                ('name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(error_messages={'unique': '\u76f8\u540c\u624b\u673a\u53f7\u5df2\u5b58\u5728'}, max_length=11, unique=True, verbose_name='\u624b\u673a\u53f7')),
                ('address', models.CharField(max_length=100, verbose_name='\u901a\u8baf\u5730\u5740')),
                ('postal_code', models.CharField(max_length=10, verbose_name='\u90ae\u7f16')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u4fe1\u606f',
                'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u79d1\u76ee',
                'verbose_name_plural': '\u6388\u8bfe\u79d1\u76ee',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(1, '\u7537'), (2, '\u5973')], verbose_name='\u6027\u522b')),
                ('mobile', models.CharField(error_messages={'unique': '\u76f8\u540c\u624b\u673a\u53f7\u5df2\u5b58\u5728'}, max_length=11, unique=True, verbose_name='\u624b\u673a\u53f7')),
                ('name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('birthday', models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('from_province', models.CharField(max_length=50, verbose_name='\u6765\u81ea\u7701\u4efd')),
                ('education', models.SmallIntegerField(choices=[(1, '\u5927\u4e13\u4ee5\u4e0b'), (2, '\u5927\u4e13\u5728\u8bfb'), (3, '\u5927\u4e13\u6bd5\u4e1a'), (4, '\u672c\u79d1\u5728\u8bfb'), (5, '\u672c\u79d1\u6bd5\u4e1a'), (6, '\u7814\u7a76\u751f\u5728\u8bfb'), (7, '\u7855\u58eb\u5728\u8bfb'), (8, '\u7855\u58eb\u6bd5\u4e1a'), (9, '\u535a\u58eb\u5728\u8bfb'), (10, '\u535a\u58eb\u6bd5\u4e1a')], verbose_name='\u76ee\u524d\u5b66\u5386')),
                ('id_code', models.CharField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1')),
                ('school', models.CharField(max_length=50, verbose_name='\u6bd5\u4e1a\u9ad8\u6821')),
                ('specialty', models.CharField(max_length=50, verbose_name='\u4e13\u4e1a')),
                ('teach_age', models.IntegerField(blank=True, null=True, verbose_name='\u6559\u9f84')),
                ('province', models.CharField(max_length=30, verbose_name='\u7701\u4efd')),
                ('address', models.CharField(max_length=100, verbose_name='\u901a\u8baf\u5730\u5740')),
                ('postal_code', models.CharField(max_length=10, verbose_name='\u90ae\u7f16')),
                ('status', models.SmallIntegerField(choices=[(1, '\u5f85\u5ba1\u6838'), (2, '\u5ba1\u6838\u4e2d'), (3, '\u5ba1\u6838\u901a\u8fc7'), (4, '\u5ba1\u6838\u5931\u8d25')], default=1, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('pass_datetime', models.DateTimeField(blank=True, null=True, verbose_name='\u5ba1\u6838\u901a\u8fc7\u65f6\u95f4')),
                ('id_code_pic', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='\u8eab\u4efd\u8bc1')),
                ('info', models.TextField(blank=True, null=True, verbose_name='\u81ea\u6211\u63cf\u8ff0')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u8be6\u60c5\u63cf\u8ff0')),
                ('cert', models.TextField(blank=True, null=True, verbose_name='\u83b7\u5f97\u8bc1\u4e66')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='\u5bb6\u6559\u7b80\u5386')),
                ('life_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_area', to='users.District', verbose_name='\u751f\u6d3b\u4f4f\u6240')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Position', verbose_name='\u76ee\u524d\u8eab\u4efd')),
                ('price', models.ManyToManyField(to='users.Price', verbose_name='\u85aa\u6c34\u8981\u6c42')),
                ('subjects', models.ManyToManyField(to='users.Subject', verbose_name='\u53ef\u6388\u79d1\u76ee')),
                ('teach_area', models.ManyToManyField(to='users.District', verbose_name='\u53ef\u6388\u8bfe\u533a\u57df')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6559\u5e08\u4fe1\u606f',
                'verbose_name_plural': '\u6559\u5e08\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u65b9\u5f0f',
                'verbose_name_plural': '\u6388\u8bfe\u65b9\u5f0f',
            },
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='way',
            field=models.ManyToManyField(to='users.Way', verbose_name='\u53ef\u6388\u8bfe\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='work_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_area', to='users.District', verbose_name='\u5de5\u4f5c\u4f4f\u6240'),
        ),
    ]
