# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '\u6559\u5e08'), (2, '\u5b66\u751f')], null=True, verbose_name='\u7c7b\u522b'),
        ),
    ]
