# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacherprofile_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='headimgs', verbose_name='\u5934\u50cf'),
        ),
    ]
