# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacherprofile_head_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='\u90ae\u7bb1'),
            preserve_default=False,
        ),
    ]
