# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teacherprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='\u540d\u5b57')),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(1, '\u6b63\u5728\u5ba1\u6838'), (2, '\u5ba1\u6838\u901a\u8fc7'), (3, '\u5ba1\u6838\u5931\u8d25')], default=1, verbose_name='\u72b6\u6001')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_set', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserComment', verbose_name='\u8bc4\u8bba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6559\u5e08\u8bc4\u4ef7',
                'verbose_name_plural': '\u6559\u5e08\u8bc4\u4ef7',
            },
        ),
    ]
