from .user import UserViewSet
from .district import DistrictViewSet
from .position import PositionViewSet
from .school import SchoolViewSet
from .price import PriceViewSet
from .subject import SubjectViewSet
from .way import WayViewSet
from .teacher_profile import TeacherProfileViewSet
from .user_comment import UserCommentViewSet
