# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_teacherprofile_teach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('district_des', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u6388\u8bfe\u5730\u533a\u8be6\u7ec6\u63cf\u8ff0')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '\u7537'), (2, '\u5973'), (3, '\u5747\u53ef')], null=True, verbose_name='\u6027\u522b')),
                ('subject', models.CharField(max_length=100, verbose_name='\u6c42\u6559\u5b66\u79d1')),
                ('class_begin', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u53ef\u4e0a\u8bfe\u65f6\u95f4')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5b66\u5458\u60c5\u51b5\u63cf\u8ff0')),
                ('teacher_gender', models.SmallIntegerField(blank=True, choices=[(1, '\u7537'), (2, '\u5973'), (3, '\u5747\u53ef')], null=True, verbose_name='\u6027\u522b')),
                ('teacher_des', models.TextField(blank=True, null=True, verbose_name='\u5bf9\u6559\u5458\u5176\u4ed6\u8981\u6c42')),
                ('charge', models.CharField(max_length=50, verbose_name='\u6536\u8d39\u8981\u6c42')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.District', verbose_name='\u6240\u5728\u533a\u57df')),
            ],
            options={
                'verbose_name': '\u8bf7\u5bb6\u6559-\u4e0b\u5355',
                'verbose_name_plural': '\u8bf7\u5bb6\u6559-\u4e0b\u5355',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u5e74\u7ea7\u540d\u79f0')),
            ],
            options={
                'verbose_name': ('\u5e74\u7ea7',),
                'verbose_name_plural': '\u5e74\u7ea7',
            },
        ),
        migrations.AddField(
            model_name='engage',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Grade', verbose_name='\u5e74\u7ea7'),
        ),
        migrations.AddField(
            model_name='engage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
