# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engage',
            name='code',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='\u8ba2\u5355\u53f7'),
            preserve_default=False,
        ),
    ]
