# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_engage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='engage',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
