# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0004_choiceteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceteacher',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to=settings.AUTH_USER_MODEL, verbose_name='\u5b66\u5458'),
            preserve_default=False,
        ),
    ]
